# Generated by Django 3.1.7 on 2021-03-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklist',
            old_name='aothor',
            new_name='author',
        ),
        migrations.AddField(
            model_name='booklist',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
